export default {
  leadFetched: 'LEAD_FETCHED',
  cancelPurchase: 'CANCEL_PURCHASE',
  changeBikeColor: 'CHANGE_BIKE_COLOR',
  toggleAccessorySelection: 'TOGGLE_ACCESSORY_SELECTION',
  startedFetchingLead: 'STARTED_FETCHING_LEAD',
  deliveryFetched: 'DELIVERY_FETCHED',
  startedFetchingDelivery: 'STARTED_FETCHING_DELIVERY',
  appointmentFetched: 'APPOINTMENT_FETCHED',
  startedFetchingAppointment: 'STARTED_FETCHING_APPOINTMENT',
  plateRegistrationFetched: 'PLATE_REGISTRATION_FETCHED',
  startedFetchingPlateRegistration: 'STARTED_FETCHING_PLATE_REGISTRATION',
  insuranceSelected: 'INSURANCE_SELECTED',
  insuranceOptOut: 'INSURANCE_OPT_OUT',
  insuranceChoiceFetched: 'INSURANCE_CHOICE_FETCHED',
  startedFetchingInsuranceChoice: 'STARTED_FETCHING_INSURANCE_CHOICE',
  financingSelected: 'FINANCING_SELECTED',
  financingChanged: 'FINANCING_CHANGED',
  startedFetchingFinancing: 'STARTED_FETCHING_FINANCING',
};
